#! /usr/bin/env bash
echo "== put object"

if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi

BUCKET_NAME=$1

https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html
aws s3api put-objectkkllll \
    --bucket "$BUCKET_NAME"